#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4D17C995CD9775F2 (letsencrypt-client@eff.org)
#
Name     : josepy
Version  : 1.1.0
Release  : 14
URL      : https://pypi.python.org/packages/b6/19/d6bee2676ce84d7ea2ea2ee1fb16cf63024afcc1e3c9455ea3e044f77318/josepy-1.1.0.tar.gz
Source0  : https://pypi.python.org/packages/b6/19/d6bee2676ce84d7ea2ea2ee1fb16cf63024afcc1e3c9455ea3e044f77318/josepy-1.1.0.tar.gz
Source99 : https://pypi.python.org/packages/b6/19/d6bee2676ce84d7ea2ea2ee1fb16cf63024afcc1e3c9455ea3e044f77318/josepy-1.1.0.tar.gz.asc
Summary  : JOSE protocol implementation in Python
Group    : Development/Tools
License  : Apache-2.0
Requires: josepy-bin = %{version}-%{release}
Requires: josepy-license = %{version}-%{release}
Requires: josepy-python = %{version}-%{release}
Requires: josepy-python3 = %{version}-%{release}
Requires: cryptography
Requires: pyOpenSSL
Requires: setuptools
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : cryptography
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyOpenSSL
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
In order for josepy.test_util._guess_loader to work properly, make sure
to use appropriate extension for vector filenames: .pem for PEM and
.der for DER.

%package bin
Summary: bin components for the josepy package.
Group: Binaries
Requires: josepy-license = %{version}-%{release}

%description bin
bin components for the josepy package.


%package license
Summary: license components for the josepy package.
Group: Default

%description license
license components for the josepy package.


%package python
Summary: python components for the josepy package.
Group: Default
Requires: josepy-python3 = %{version}-%{release}

%description python
python components for the josepy package.


%package python3
Summary: python3 components for the josepy package.
Group: Default
Requires: python3-core

%description python3
python3 components for the josepy package.


%prep
%setup -q -n josepy-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541267084
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/josepy
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/josepy/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jws

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/josepy/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
