#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC795956FB489DCA9 (jannis@leidel.info)
#
Name     : josepy
Version  : 1.0.1
Release  : 1
URL      : https://pypi.python.org/packages/44/85/8a6a4d6decb8bb66df4c5691f963c335fc3ee973a1c7a9825794e9d49e08/josepy-1.0.1.tar.gz
Source0  : https://pypi.python.org/packages/44/85/8a6a4d6decb8bb66df4c5691f963c335fc3ee973a1c7a9825794e9d49e08/josepy-1.0.1.tar.gz
Source99 : https://pypi.python.org/packages/44/85/8a6a4d6decb8bb66df4c5691f963c335fc3ee973a1c7a9825794e9d49e08/josepy-1.0.1.tar.gz.asc
Summary  : JOSE protocol implementation in Python
Group    : Development/Tools
License  : Apache-2.0
Requires: josepy-bin
Requires: josepy-python3
Requires: josepy-python
Requires: Sphinx
Requires: coverage
Requires: cryptography
Requires: flake8
Requires: pytest
Requires: pytest-cov
Requires: python-mock
Requires: setuptools
Requires: six
Requires: sphinx_rtd_theme
Requires: tox
BuildRequires : cryptography
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyOpenSSL
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
In order for josepy.test_util._guess_loader to work properly, make sure
to use appropriate extension for vector filenames: .pem for PEM and
.der for DER.

%package bin
Summary: bin components for the josepy package.
Group: Binaries

%description bin
bin components for the josepy package.


%package python
Summary: python components for the josepy package.
Group: Default
Requires: josepy-python3

%description python
python components for the josepy package.


%package python3
Summary: python3 components for the josepy package.
Group: Default
Requires: python3-core

%description python3
python3 components for the josepy package.


%prep
%setup -q -n josepy-1.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522516149
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jws

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
